sudo: required
install: gradle wrapper
language: java
jdk: oraclejdk8
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in naresh-app.json.enc -out naresh-app.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file naresh-app.json
  # Read note.txt file  for details on how to create a Services account, Download Services acount in json file etc.
  - chmod +x gradlew
  - export TZ=America/New_York
  - gcloud config set project naresh-app-229804 
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t programmer26/naresh-web -f ./client/Dockerfile ./client


script:
  - ./gradlew clean cleanTest test --info

deploy:
  provider: script
  script: bash ./build.sh
  on:
branch: master