apiVersion: v1
kind: Deployment
metadata: 
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchlabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: programmer26/some-image-name
          ports:
            - containerPort: 3000
          env:
             - name: PGUSER
               value: postgres
             - name: PGHOST
               value: postgres-cluster-ip-service
             - name: PGPORT
               value: '5432'
             - name: PGDATABASE
               value: postgres
             - name: PGPASSWORD
               valueFrom:
                 secretKeyRef:
                   name: pgpassword
                   key: PGPASSWORD













